package com.hotel_management.domain.enums;

public enum RoomCategory {
    SINGLE_1P_STANDARD,
    SINGLE_1P_DELUXE,
    SINGLE_1P_SUITE,
    DOUBLE_2P_STANDARD,
    DOUBLE_2P_DELUXE,
    DOUBLE_2P_SUITE,
    TRIPLE_3P_STANDARD,
    TRIPLE_3P_DELUXE,
    TRIPLE_3P_SUITE,
    FAMILY_4P_STANDARD,
    FAMILY_4P_DELUXE,
    FAMILY_4P_SUITE
}
